# Generated by Django 4.2.6 on 2024-01-16 16:36

import authentication.helpers
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authentication', '0004_membersmodel_otp'),
    ]

    operations = [
        migrations.CreateModel(
            name='emergencyContactsModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('icon', models.FileField(default='default-profile.png', upload_to=authentication.helpers.custom_file_name)),
                ('name', models.CharField(max_length=255)),
                ('number', models.CharField(max_length=20, unique=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='eventsModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('img', models.ImageField(default='default-profile.png', upload_to=authentication.helpers.custom_file_name)),
                ('event_name', models.CharField(max_length=255)),
                ('event_description', models.TextField(max_length=255)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='galleryModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('gallery_img', models.ImageField(default='default-profile.png', upload_to=authentication.helpers.custom_file_name)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='services',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='clubHouseBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('event_name', models.CharField(max_length=255)),
                ('from_date', models.DateField(max_length=30)),
                ('to_date', models.DateField(max_length=30)),
                ('content', models.TextField()),
                ('total_days', models.IntegerField(blank=True)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved')], default='Pending', max_length=50)),
                ('description', models.TextField(max_length=255)),
                ('member_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authentication.membersmodel')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
