# Generated by Django 4.2.6 on 2023-10-17 07:18

import authentication.helpers
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membersmodel',
            name='password',
            field=models.CharField(default=authentication.helpers.generate_password, max_length=255),
        ),
    ]
