# Generated by Django 4.2.6 on 2023-10-27 05:10

import authentication.helpers
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_alter_membersmodel_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='memberprofilemodel',
            name='profile',
            field=models.FileField(default='default-profile.png', upload_to=authentication.helpers.custom_file_name),
        ),
    ]
